### PR TITLE
Support CocoaPods

### PR DESCRIPTION
**Pull request by ahizzle**

### CODE REVIEW

**Comment by esutton** [comment]
@ahizzle Thank you.  I hope this gets merged soon.

This is badly needed since react native >= 0.60 is using pods for everything.  

Without a podspec, I cannot figure out how to solve the following error since React is already included in my project's Podfile.
````
/node_modules/react-native-tcp/ios/TcpSockets.m:6:9: fatal error: 'React/RCTAssert.h' file not found
#import <React/RCTAssert.h>
````

**Comment by phillbaker** [comment]
@ahizzle @esutton I recently started helping to maintain this package, maintenance has moved to a fork. Mind repointing your PR to https://github.com/aprock/react-native-tcp? I have contributor permission there.

**Comment by esutton** [comment]
@phillbaker thanks for the tip.

I am using @ahizzle fork since I need pod support now.
````
    "react-native-tcp": "https://github.com/atvenu/react-native-tcp.git",
````

**Comment by ahizzle** [comment]
I've opened a PR for the aprock fork.

**Pull request closed without merging**
