### PR TITLE
Replace `this` by `self` in a scoped reference

### PR DESCRIPTION
**Pull request by jsdario**
Crashes if accessing the variable

### CODE REVIEW

**Comment by crearc** [comment]
@aprock can you please merge this? I confirmed that this is a good fix.

**Comment by aprock** [comment]
sorry I don't actually have write access to this repository anymore.
@sivaatpeel could you merge?

**Comment by inder123** [comment]
@aprock  Given you write access.

**Comment by crearc** [comment]
Would be great if either of you could merge. :)

**Comment by aprock** [comment]
I'm working on getting permission from my current employer to contribute back to this project.  will merge as soon as the legal dept. approves.

**Pull request merged**
